spring:
  datasource:
    url: jdbc:mysql://192.168.44.167:3306/test?useUnicode=true&characterEncoding=UTF-8
    username: vmuser
    password: cp@1234567890
    driver-class-name: com.mysql.cj.jdbc.Driver
